language: go
go:
  - 1.8.x
  - tip
notifications:
  email: false

addons:
  apt:
    sources:
    - sourceline: 'ppa:masterminds/glide'
    packages:
    - glide

before_install:
  - openssl aes-256-cbc -K $encrypted_46ebb92479eb_key -iv $encrypted_46ebb92479eb_iv -in ionline-test-firebase-adminsdk-vslf8-adbc081cb9.json.enc -out ionline-test-firebase-adminsdk-vslf8-adbc081cb9.json -d

install:
  - #Do Nothing to prevent go get ./...

before_script:
  - glide install -v

script:
  - ./build_travis.sh
